repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_docs_replace
