---
- hosts: default
  become: true

  vars:
    cfssl_version: "1.4.1"

  tasks:
    - name: "Install common packages"
      include_role:
        name: "{{ playbook_dir }}/../../provisioners/roles/install-pkg"

    - name: "Install cfssl binaries"
      include_role:
        name: "{{ playbook_dir }}/../../provisioners/roles/install-cfssl"
