---
- name: Install required packages
  become: true
  package:
    name: "{{ required_packages }}"
    state: present

- name: Set timezone to {{ system_timezone }}
  become: true
  timezone:
    name: "{{ system_timezone }}"
